### ISSUE TITLE
Error in get(as.character(FUN), mode = "function", envir = envir) : object 'bind_rows' of mode 'function' was not found

### ISSUE THREAD

**Issue by 0815pascal** [JesseVent/crypto#34] opened 2018-11-04 20:28 UTC
Basically when trying the crypto_history function in R-Studio I'm getting this error

## Detailed Description

Here's the code I've used

```
library(crypto)
library(foreach)
library(rvest)
library(xml2)

will_i_get_rich <- crypto_history(limit=50)
```

And here's the output: 

```
 |                                                                                    |   0%   If this helps you become rich please consider donating
ERC-20: 0x375923Bf82F0b728d23A5704261a6e16341fd860
XRP: rK59semLsuJZEWftxBFhWuNE6uhznjz2bK
LTC: LWpiZMd2cEyqCdrZrs9TjsouTLWbFFxwCj
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'bind_rows' of mode 'function' was not found

```

Since I'm rather a rookie user I'd be glad if you could help me understanding what's wrong

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4): RStudio Version 1.1.456 
* Operating System and version (desktop or mobile): OsX 10.14 Mojave

**Comment by 0815pascal** [comment] 2018-11-04 20:54
I could solve the problem after 

[devtools::install_github("JesseVent/crypto")
](url) and 
loading _dplyr_. 

Don't know what has made it work, but now it's all fine again.

**Comment by JesseVent** [comment] 2018-11-10 09:43
duplicate of #28 

Issue was due to the function bind_rows from the dplyr package not being loaded. 
Github version has fix for it, otherwise for CRAN installed version running `library(dplyr)` before loading `library(crypto)` would have worked.

**Closed by JesseVent** 2018-11-10 09:43 UTC
Labels: duplicate
